### PR TITLE
Javadoc for Expect Score interfaces.

### PR DESCRIPTION
**Pull request by balhoff**

### CODE REVIEW

**Comment by hlapp** [comment]
@balhoff - I know you spoke about the methods with Callie, but could you please include in the documentation for each method _what_ the method is supposed to do? Right now I only see documentation for the method parameters, not for the methods' supposed actions themselves.

**Comment by hlapp** [comment]
@balhoff you may have seen that this pull request had a merge conflict. The conflict was easy enough to resolve so I was going to walk @calliem through how to do that when the code to be reconciled is on a fork's branch. However, I also needed to the fork up to date, and because you had put the changes on the master branch I had no way but to resolve the conflict myself. Because of the conflict resolving merge commit, all of @calliem's commits now show up under this pull request, which is quite odd at best.

Could you please in the future put all changes destined for a PR on a new branch, and not master? Also, I'm closing this one and redoing it from a fresh branch (see #4). I'll move the above comment over; obviously, please add commits to the branch the pull request is on, not master.

**Comment by hlapp** [comment]
I notice that I can't actually close (or withdraw) this PR. @calliem - can you close (= refuse, not merge) it?

**Comment by calliem** [comment]
Closed the pull request

**Pull request closed without merging**
